# Dockerfile.frontend.dev
FROM node:20-alpine AS dev
WORKDIR /app

# Copiamos solo package.json y package-lock.json para aprovechar cache
COPY package*.json ./
RUN npm ci

# Copiamos el resto del código
COPY . .

# Exponemos el puerto de Angular
EXPOSE 4200

# Comando para levantar Angular en modo desarrollo
CMD ["npm", "start", "--", "--host", "0.0.0.0"]
